name: Build and Push Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "$DOCKER_TOKEN" | docker login -u "franeklasinski" --password-stdin
        env:
          DOCKER_TOKEN: your-docker-token

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: franeklasinski/ml-api:latest
